version: '3.8'

services:
  postgres:
    # image: postgres:latest
    
    # for the case when vector
    image: ankane/pgvector:latest
    container_name: postgres-ai
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: